### ISSUE TITLE
CMAKE option to make MSVC use /MT and /MTd for Release and Debug builds respectively

### ISSUE THREAD

**Issue by cjserio** [backtrace-labs/crashpad#16]
Right now if you follow the instructions "cmake -G "Visual Studio 16 2019" .." you end up with all of the projects using /MD and /MDd. I've been struggling to find a way to force the project to use /MT and /MTd for Release and Debug builds respectively.

**Comment by vlussenburg** [comment]
Thanks for the feedback! I'll follow up once we've discussed this.

**Comment by vlussenburg** [comment]
This may be useful:
https://stackoverflow.com/questions/55302553/how-to-build-dynamic-shared-libraries-of-crashpad

**Comment by cjserio** [comment]
That seems to be for Ninja, not CMAKE. [The ZIP file](http://get.backtrace.io/crashpad/builds/) available on the bactrace.io for MSVC has a lib_MT and lib_MD folder. I was really just wondering how that lib_MT was built. What CMAKE options were used?

**Comment by vlussenburg** [comment]
Hello! Those are built pre-CMake. It will likely require massaging the
CMake files so that those parameters are injected based on the environment,
but we’ll have to discuss this internally in the next week(s). In the
meantime, feel free to fork the repo and if you figure it out before us, to
submit a PR!

**Comment by cjserio** [comment]
Pull request sent! 👍

**Comment by vlussenburg** [comment]
Thanks! We will review it soon!!
