### ISSUE TITLE
crashpad generates c_fltSave with floating-point/simd registers, but Backtrace only displays integer registers

### ISSUE THREAD

**Issue by alecazam** [backtrace-labs/crashpad#50]
Being able to view fp/simd registers is important.  We have extensive use of floating point and simd (SSE/Neon) code.

**Comment by alecazam** [comment]
Also can't toggle these integer registers off hex in the web display.

**Comment by rick-bt** [comment]
Hi @alecazam - This is a good question, but we'd like to keep this issues channel focused on questions specific to this code base. This particular question is about Backtrace functionality in general, and we'd like to drive it through standard support channels rather than engaging engineers in support. I'm going to close this issue. Please check out our documentation at https://docs.saucelabs.com/error-reporting/getting-started/ or send an email to [support@backtrace.io](mailto:support@backtrace.io). 

Your [other issue](https://github.com/backtrace-labs/crashpad/issues/49) is solid though, and dev will dig into that when possible.
